version: '3.8'
services:
  player-service:
    build: ./services/player-service
    ports:
      - "8080:8080"
    environment:
      - HTTP_PORT=8080
    networks:
      - minecraft-network
    depends_on:
      - postgres

#  matchmaking-service:
#    build: ./services/matchmaking-service
#    ports:
#      - "8082:8080"
#    networks:
#      - minecraft-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: opt
    ports:
      - "5432:5432"
    networks:
      - minecraft-network

networks:
  minecraft-network:
    driver: bridge
