version: '3.8'
services:
  player-service:
    build: ./user-authentication-service
    ports:
      - "8080:8080"
    environment:
      - HTTP_PORT=8080
      - CONTEXT_PATH=/player
    networks:
      - minecraft-network
    depends_on:
      - mysql
#
#  matchmaking-service:
#    build: ./matchmaking-service
#    ports:
#      - "8082:8080"
#    networks:
#      - minecraft-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
    ports:
      - "3306:3306"
    networks:
      - minecraft-network

networks:
  minecraft-network:
    driver: bridge
