version: '3.8'
# temporary development compose

services:
  player-service:
    image: player-service:0.0.1
    build: ./services/player-service
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    networks:
      - minecraft-network
    env_file:
      - .env
      - ./services/player-service/.env
    depends_on:
      - postgres

#  matchmaking-service:
#    build: ./services/matchmaking-service
#    ports:
#      - "8082:8080"
#    networks:
#      - minecraft-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # use secrets in future
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "45432:45432"
    env_file:
      - ./services/player-service/.env
    networks:
      - minecraft-network

networks:
  minecraft-network:
    driver: bridge
